package com.example.sarthak.sanuti.Activities.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.ArrayList;
import java.util.List;

/**
 * Entity mapped to table "LIKES".
 */
public class Likes {


  List<String> likes=new ArrayList<>();
  public Likes()
  {

  }

    public Likes(List<String> likes) {
        this.likes = likes;
    }

    public List<String> getLikes() {
        return likes;
    }

}
