package com.example.sarthak.sanuti.Activities.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 



import android.graphics.Bitmap;

import java.io.Serializable;


public class User implements Serializable {

    private Long id;
    private String firstName;
    private String lastName;
    private String dob;
    private String gentoshow;
    private String connections;
    private String hold;
    private String request;
    private String rejected;
    private String location;
    private String gender;
    private String email;
    private String userId;
    private String pic1;
    private String pic2;
    private String pic3;
    private String pic4;
    private String pic5;
    private String pic6;
    private String likes;
    private String last_seen;
    private Integer age_flag;
    private Integer dist_flag;
    private String trust_score;
    private String mb_number;
    private String about_me;
    Bitmap bmp;

    public Bitmap getBmp() {
        return bmp;
    }

    public void setBmp(Bitmap bmp) {
        this.bmp = bmp;
    }

    private String interests;

    public String getLati() {
        return lati;
    }

    public void setLati(String lati) {
        this.lati = lati;
    }

    public String getLongi() {
        return longi;
    }

    public void setLongi(String longi) {
        this.longi = longi;
    }

    private String lati;
    private String longi;
    private String work_info;
    private String edu_details;
    private String doj;
    private String intrest;

    public String getGentoshow() {
        return gentoshow;
    }

    public void setGentoshow(String gentoshow) {
        this.gentoshow = gentoshow;
    }

    public String getConnections() {
        return connections;
    }

    public void setConnections(String connections) {
        this.connections = connections;
    }

    public String getHold() {
        return hold;
    }

    public void setHold(String hold) {
        this.hold = hold;
    }

    public String getRequest() {
        return request;
    }

    public void setRequest(String request) {
        this.request = request;
    }

    public String getRejected() {
        return rejected;
    }

    public void setRejected(String rejected) {
        this.rejected = rejected;
    }

    public User(Long id, String firstName, String lastName, String dob, String location, String gender, String email, String userId, String pic1, String pic2, String pic3, String pic4, String pic5, String pic6, String likes, String last_seen, Integer age_flag, Integer dist_flag, String trust_score, String mb_number, String about_me, String interests, String hobbies, String work_info, String edu_details, String doj) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.dob = dob;
        this.location = location;
        this.gender = gender;
        this.email = email;

        this.userId = userId;
        this.pic1 = pic1;
        this.pic2 = pic2;
        this.pic3 = pic3;
        this.pic4 = pic4;
        this.pic5 = pic5;
        this.pic6 = pic6;
        this.likes = likes;
        this.last_seen = last_seen;
        this.age_flag = age_flag;
        this.dist_flag = dist_flag;
        this.trust_score = trust_score;
        this.mb_number = mb_number;
        this.about_me = about_me;
        this.interests = interests;

        this.work_info = work_info;
        this.edu_details = edu_details;
        this.doj = doj;
    }

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public String getIntrest() {
        return intrest;
    }

    public void setIntrest(String intrest) {
        this.intrest = intrest;
    }


    public String getLikes() {
        return likes;
    }

    public void setLikes(String likes) {
        this.likes = likes;
    }

    public String getPic1() {
        return pic1;
    }

    public void setPic1(String pic1) {
        this.pic1 = pic1;
    }

    public String getPic2() {
        return pic2;
    }

    public void setPic2(String pic2) {
        this.pic2 = pic2;
    }

    public String getPic3() {
        return pic3;
    }

    public void setPic3(String pic3) {
        this.pic3 = pic3;
    }

    public String getPic4() {
        return pic4;
    }

    public void setPic4(String pic4) {
        this.pic4 = pic4;
    }

    public String getPic5() {
        return pic5;
    }

    public void setPic5(String pic5) {
        this.pic5 = pic5;
    }

    public String getPic6() {
        return pic6;
    }

    public void setPic6(String pic6) {
        this.pic6 = pic6;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getDob() {
        return dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }



    public String getLast_seen() {
        return last_seen;
    }

    public void setLast_seen(String last_seen) {
        this.last_seen = last_seen;
    }

    public Integer getAge_flag() {
        return age_flag;
    }

    public void setAge_flag(Integer age_flag) {
        this.age_flag = age_flag;
    }

    public Integer getDist_flag() {
        return dist_flag;
    }

    public void setDist_flag(Integer dist_flag) {
        this.dist_flag = dist_flag;
    }

    public String getTrust_score() {
        return trust_score;
    }

    public void setTrust_score(String trust_score) {
        this.trust_score = trust_score;
    }

    public String getMb_number() {
        return mb_number;
    }

    public void setMb_number(String mb_number) {
        this.mb_number = mb_number;
    }

    public String getAbout_me() {
        return about_me;
    }

    public void setAbout_me(String about_me) {
        this.about_me = about_me;
    }

    public String getInterests() {
        return interests;
    }

    public void setInterests(String interests) {
        this.interests = interests;
    }




    public String getWork_info() {
        return work_info;
    }

    public void setWork_info(String work_info) {
        this.work_info = work_info;
    }

    public String getEdu_details() {
        return edu_details;
    }

    public void setEdu_details(String edu_details) {
        this.edu_details = edu_details;
    }

    public String getDoj() {
        return doj;
    }

    public void setDoj(String doj) {
        this.doj = doj;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", dob='" + dob + '\'' +
                ", location='" + location + '\'' +
                ", gender='" + gender + '\'' +
                ", email='" + email + '\'' +
                ", userId='" + userId + '\'' +

                ", last_seen='" + last_seen + '\'' +
                ", age_flag=" + age_flag +
                ", dist_flag=" + dist_flag +
                ", trust_score='" + trust_score + '\'' +
                ", mb_number='" + mb_number + '\'' +
                ", about_me='" + about_me + '\'' +
                ", interests='" + interests + '\'' +

                ", work_info='" + work_info + '\'' +
                ", edu_details='" + edu_details + '\'' +
                ", doj='" + doj + '\'' +
                '}';
    }
}
